services:
  - type: web
    name: wolfit
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: wolfit-database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: wolfit-database
          property: port
      - key: DB_NAME
        fromDatabase:
          name: wolfit-database
          property: database
      - key: DB_USER
        fromDatabase:
          name: wolfit-database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: wolfit-database
          property: password
      - key: UPSTASH_REDIS_REST_URL
        value: "https://diverse-redfish-15494.upstash.io"
      - key: UPSTASH_REDIS_REST_TOKEN
        value: "ATyGAAIncDJjYmIxZTRiZGYyNWE0OWI4OGZhYTYyNDhjM2U3NTVmN3AyMTU0OTQ"

databases:
  - name: wolfit-database
    databaseName: wolfit
    user: wolfit_user
